from tkinter import *

window = Tk()

window.geometry("500x500")
window.title("Calculator")
equation = StringVar()
expression_field = Entry(window, textvariable=equation)
expression_field.grid(columnspan=8, ipadx=80)
equation.set('Enter Values')

button1 = Button(text="1", bg="red", width=7, height=2)
button2 = Button(text="2", bg="red", width=7, height=2)
button3 = Button(text="3", bg="red", width=7, height=2)
button4 = Button(text="4", bg="red", width=7, height=2)
button5 = Button(text="5", bg="red", width=7, height=2)
button6 = Button(text="6", bg="red", width=7, height=2)
button7 = Button(text="7", bg="red", width=7, height=2)
button8 = Button(text="8", bg="red", width=7, height=2)
button9 = Button(text="9", bg="red", width=7, height=2)
button0 = Button(text="0", bg="red", width=7, height=2)
button_plus = Button(text="+", bg="red", width=7, height=2)
button_minus = Button(text="-", bg="red", width=7, height=2)
button_mul = Button(text="*", bg="red", width=7, height=2)
button_div = Button(text="/", bg="red", width=7, height=2)

button1.grid(row=2, column=0)
button2.grid(row=2, column=1)
button3.grid(row=2, column=2)
button4.grid(row=3, column=0)
button5.grid(row=3, column=1)
button6.grid(row=3, column=2)
button7.grid(row=4, column=0)
button8.grid(row=4, column=1)
button9.grid(row=4, column=2)
button0.grid(row=5, column=1)
button_plus.grid(row=2, column=4)
button_minus.grid(row=3, column=4)
button_mul.grid(row=4, column=4)
button_div.grid(row=5, column=4)

window.mainloop()
